// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xkxufwubibaxlrayoqrn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhreHVmd3ViaWJheGxyYXlvcXJuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE0NTkzNDEsImV4cCI6MjA2NzAzNTM0MX0.E8kKqnKDpr6LlbvO4l7TaeZPt0y_tibh8qXPHbQLh_4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});